import Head from "next/head";
import DarkModeToggle from "../components/common/DarkModeToggle";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="height-60 bg-slate-500 dark:bg-slate-800 ">
        <div className="container mx-auto flex justify-between p-2">
          <div className="flex items-center">
            <h1 className="text-2xl font-bold">Next.js + Tailwind CSS</h1>
          </div>
          <div className="flex items-center relative">
            <DarkModeToggle />
          </div>
        </div>
      </header>
    </>
  );
}
